"""price and text

Revision ID: 20029e1cceb9
Revises: 
Create Date: 2024-07-26 21:48:26.445644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20029e1cceb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=140), nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('text')

    # ### end Alembic commands ###
