"""price and text

Revision ID: 23724534145e
Revises: 20029e1cceb9
Create Date: 2024-07-26 21:49:43.791029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23724534145e'
down_revision = '20029e1cceb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('text', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ad_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_user_id'))
        batch_op.drop_index(batch_op.f('ix_ad_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ad_category_id'))

    op.drop_table('ad')
    # ### end Alembic commands ###
